import { defineConfig } from 'astro/config';
import mdx from '@astrojs/mdx';
// Sitemap is generated by a custom route (src/pages/sitemap-0.xml.ts) so we can
// compute per-URL lastmod from frontmatter pubDate. The @astrojs/sitemap
// integration has been removed; a small custom route replaces it.
import UnoCSS from '@unocss/astro';
import cicadaGrammar from './src/shiki/cicada.tmLanguage.json';

export default defineConfig({
  site: 'https://runany.dev',
  output: 'static',
  trailingSlash: 'always',
  integrations: [
    mdx(),
    UnoCSS({ injectReset: true }),
  ],
  markdown: {
    shikiConfig: {
      theme: 'github-dark',
      wrap: true,
      langs: [
        {
          id: 'cicada',
          scopeName: 'source.cicada',
          aliases: ['cicada'],
          grammar: cicadaGrammar,
        },
      ],
    },
  },
});
